upgrades = [
    {
        name:"make mod hirers 10x better (9e-7 mods)",
        onbuy:()=>{generatorProduction[0]=generatorProduction[0].times(10)},
        checkforunlock:()=>{if(generators[0].gte(10)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("9e-7"),
    },
    {
        name:"make mod hirers hirers 10x better (9 mods)",
        onbuy:()=>{generatorProduction[1]=generatorProduction[1].times(10)},
        checkforunlock:()=>{if(generators[1].gte(10)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("9"),
    },
    {
        name:"make mod hirers 10x better (1e-3 mod)",
        onbuy:()=>{generatorProduction[0]=generatorProduction[0].times(10)},
        checkforunlock:()=>{if(generators[0].gte(100)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("1e-3"),
    },
    {
        name:"make mod hirers 100x better (9e-2 mod)",
        onbuy:()=>{generatorProduction[0]=generatorProduction[0].times(10)},
        checkforunlock:()=>{if(generators[0].gte(1000)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("9e-2"),
    },
    {
        name:"make mod hirers 500x better (7e-1 mods)",
        onbuy:()=>{generatorProduction[0]=generatorProduction[0].times(10)},
        checkforunlock:()=>{if(generators[0].gte(5000)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("7e-1"),
    },
    {
        name:"make mod hirers 5000x better (10 mods)",
        onbuy:()=>{generatorProduction[0]=generatorProduction[0].times(10)},
        checkforunlock:()=>{if(generators[0].gte(50000)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("10"),
    },
    {
        name:"make mod hirer hirers 10x better (100000 mods)",
        onbuy:()=>{generatorProduction[1]=generatorProduction[1].times(10)},
        checkforunlock:()=>{if(generators[1].gte(100)){return true}else{return false}},
        unlocked:false,
        pricetype:"cash",
        price:new Decimal("100000"),
    },
]
